staging: android: lowmemorykiller: Add config option to support oom_adj values
The conversion to use oom_score_adj instead of the deprecated oom_adj
values breaks existing user-space code. Add a config option to convert
oom_adj values written to oom_score_adj values if they appear to be
valid oom_adj values.

Change-Id: I68308125059b802ee2991feefb07e9703bc48549
CRs-Fixed: 389463
Signed-off-by: Arve Hjønnevåg <arve@android.com>
Signed-off-by: Laura Abbott <lauraa@codeaurora.org>

Conflicts:
	drivers/staging/android/Kconfig

This commit only updates drivers/staging/android/Kconfig because the necessary
changes to lowmemorykiller.c were already made with commit 5a297ce.

Also fixed the following error:
drivers/staging/android/lowmemorykiller.c:287:43: error: negative width in bit-field '<anonymous>'

Conflicts:
	drivers/staging/android/lowmemorykiller.c